apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: live
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
        app: nginx-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
