apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
  namespace: live
  labels:
    app: nginx-app
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
  - name: http
    port: 8001
    protocol: TCP
    targetPort: 80
