apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
  namespace: live
  labels:
    app: hello-app
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
  - name: http
    port: 8002
    protocol: TCP
    targetPort: 8080
