apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-blue-svc
  labels:
    app: k8s-demo
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30060
  selector:
    app: k8s-demo
    name: k8s-demo-blue
    namespace: blue
    version: "0.1"
    type: LoadBalancer
