apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-demo-deployment
  labels:
    name: k8s-demo-blue
    namespace: blue
    version: "0.1"
spec:
  replicas: 10
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
        - name: k8s-demo-pod
          image: k8s-demo:0.2
          ports:
            - containerPort: 80