################################################################################
apiVersion: v1
kind: Namespace
metadata:
  name: spring-boot-app-with-nginx

################################################################################
appVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-app-with-nginx-proxy-config-v1
# Custom nginx Configuration to override default configuration in Nginx container
data:
  proxy.conf: |-
    # HTTP 1.1 support
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Host $http_host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $proxy_connection;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
    proxy_read_timeout 10m;
    client_max_body_size 25m;
  nginx.conf: |-
    user  nginx;
    worker_processes  2;
    daemon off;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
        multi_accept on;
    }

    http {
        server_names_hash_bucket_size 128;
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        keepalive_timeout  65;
        gzip  on;
        include /etc/nginx/conf.d/*.conf;
    }


################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-with-nginx
  labels:
    name: spring-boot-app-with-nginx
    version: "1.0.1"
  namespace: "dev"
  annotations:
    description: "nginx reverse proxy for spring-boot services and pods powered by annotations"

spec:
  selector:
    matchLabels:
      name: spring-boot-app-with-nginx
  template:
    metadata:
      labels:
        name: spring-boot-app-with-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
        ports:
        - containerPort: 80
        - hostPort: 81
        imagePullPolicy: "Always"
        securityContext:
          privileged: true
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      - name: app
        image: asia.gcr.io/kdeng-gae-demos/spring-boot-with-jib:latest
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: ./log
      - name: varlibdockercontainers
        hostPath:
          path: ./lib/docker/containers